**2. Crear un programa en OpenCV que permita llevar a cabo operaciones de convolución de una imagen en tonos de gris, empleando una matriz cuadrada de números en coma flotante, de tamaño variable. Dicha matriz tendrá un tamaño arbitrario y se especificará como una lista de listas de la siguiente forma:**

```python
convolucion = [[-1.0,0.0,1.0],[-1.0,0.0,1.0],[-1.0,0.0,1.0]]
```

**El propio programa será encargado de normalizar el resultado para que se encuentre en el rango 0-255, y de visualizar tanto la imagen original como la imagen convolucionada. Indique en los comentarios del programa la estrategia empleada en el proceso de normalización.**

![Convolucion](convolucion.png)
_Figura 1. Operación de convolucion_

**Nota: Si para calcular la convolución, se accede a un pixel que esta fuera de la imagen, se considerará que ese pixel tiene valor 0**

![Solucion](p4solucion.png)
_Figura 2. Resultado de aplicar la matriz de convolución_

In [3]:
import numpy as np
import cv2, sys

nombreImagen ="p4.png"
nombreImagenResultante = "p4convolucion.png"

#cargamos la imagen
imagen = cv2.imread(nombreImagen, cv2.IMREAD_GRAYSCALE)

if (imagen is None):
    print("Error al cargar la imagen")
    sys.exit()
    
#calculamos las dimensiones
dimensiones=imagen.shape
alto = dimensiones[0]
ancho = dimensiones[1]

tamConvolucion = 3
convolucion = [[-1.0,0.0,1.0],[-1.0,0.0,1.0],[-1.0,0.0,1.0]]

#rotamos 180º la matriz de convolución
filtro = np.flip(np.flip(convolucion, 1), 0)


#####################################
#########   CONVOLUCION   ###########
#####################################

# Calculo el margen a añadir a la imagen original
margen = int(tamConvolucion/2)

# Creo una imagen con un margen de 0s a su alrededor
imagenMod = np.zeros((alto + margen*2, ancho + margen*2))
imagenMod[int(margen):int(-1 * margen), int(margen):int(-1 * margen)] = imagen

# Genero la imagen resultante vacia
imagenResultante = np.zeros((alto, ancho))

# Calculo la suma de la matriz nucleo
sumaFiltro = 0
for i in range(tamConvolucion):
    for j in range(tamConvolucion):
        sumaFiltro += filtro[i][j]

# Si es 0, la pongo a 1 para no dividir entre 0
if (sumaFiltro == 0):
    sumaFiltro = 1.0
    
# Iteramos sobre la imagen y aplicamos la formula de la convolucion sobre cada pixel
for j in range(ancho):
    for i in range(alto):
        # En esta linea ocurre la magia
        imagenResultante[i, j] = ((filtro * imagenMod[i: i + tamConvolucion, j: j + tamConvolucion]).sum() / sumaFiltro)
        # Si el valor es menor a 0 o mayor a 255 se reajusta
        if (imagenResultante[i][j] < 0):
            imagenResultante[i][j] = 0.0
        if (imagenResultante[i][j] > 255):
            imagenResultante[i][j] = 255.0
      
print (imagenResultante)

#####################################
#########   NORMALIZAR   ############
#####################################

# Valor Max y Min Intensidad Imagen
maxI = np.max(imagenResultante)
minI = np.min(imagenResultante)
# Variacion de Intensidad Imagen
k = (maxI-minI)

# Creamos una imagen vacia
img = np.zeros((alto, ancho), np.uint8)

# Multiplicamos cada pixel por la constante obtenida
for i in range(alto):
    for j in range(ancho):
        img[i][j] = (imagenResultante[i][j]-minI)*(255/k)

#Se muestran las imagenes
cv2.imshow("Imagen Original", imagen)
cv2.imshow("Imagen Convolucionada", img)

#Se guarda la nueva imagen en un archivo
cv2.imwrite(nombreImagenResultante , imagenResultante)

#Se finaliza la ejecucion
cv2.waitKey(0)
cv2.destroyAllWindows()

[[  0.   0.   0. ...  46.  24. 234.]
 [  0.   0.   0. ...  46.  20. 255.]
 [  0.   0.   1. ...  20.   0. 255.]
 ...
 [  0.   0.   0. ...   2.   0. 255.]
 [  0.   0.   0. ...   1.   1. 255.]
 [  0.   0.   0. ...   0.   2. 255.]]


_Explicación del código:_

Lo he ido explicando conforme lo implementaba, esta todo en los comentarios